config/routes.rb
Rails.application.routes.draw do
  resources :opendays
  resources :venues

  root 'venues#index'
  
  get "platform_a/venue", to: 'apis#get_venue_a'
  get "platform_b/venue", to: 'apis#get_venue_b'
  get "platform_c/venue", to: 'apis#get_venue_c'
  
  put "platform_a/venue", to: 'apis#update_venue_a'
  put "platform_b/venue", to: 'apis#update_venue_b'
  put "platform_c/venue", to: 'apis#update_venue_c'
  

end

app/models/venue.rb
class Venue < ActiveRecord::Base


  has_many :opendays, :dependent => :destroy
  
  DAY_OF_WEEKS = [
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun"
  ]
  
  
  # Hours formated to Platform A Requirements
  def get_hours_a
    timetable = Array.new
    self.opendays.each do |item|
      timetable << item.hours     
    end
    timetable.join("|")
  end
  
  # Join two lines of adress (If exists second one)
  def get_adress
    adress = self.address2.blank? ? self.address1 : self.address1+" "+self.address2 
  end
  
  # Hours formated to Platform B Requirements
  def get_hours_b
    timetable = Array.new
    self.opendays.each do |item|
      timetable << (DAY_OF_WEEKS[item.day]+":"+item.hours)
    end
    timetable.join("|")
  end
  
  # Hours formated to Platform C Requirements
  def get_hours_c
    timetable = Array.new
    self.opendays.each do |item|
      timetable << item.hours     
    end
    timetable.join(",")
  end
  
  #Split and save open days in common format.
  #If the format received is unknow, it will be ignored
  def set_hours(hours)
    if(hours.start_with?( 'M'))
      splitted_hours = hours.split("|")
      self.opendays.destroy_all
      splitted_hours.each.with_index do |item, index|
         new_openday = Openday.create(day:index, hours:item[4,12])
         self.opendays << new_openday
      end
    elsif(hours.include?(","))
      splitted_hours = hours.split(",")
      self.opendays.destroy_all
      splitted_hours.each.with_index do |item, index|
         new_openday = Openday.create(day:index, hours:item)
         self.opendays << new_openday
      end
    
    elsif(hours.include?("|") && !hours.start_with?( 'M'))
      splitted_hours = hours.split("|")
      self.opendays.destroy_all
      splitted_hours.each.with_index do |item, index|
         new_openday = Openday.create(day:index, hours:item)
         self.opendays << new_openday
      end
    
    end
  end
  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :address1, :address2, :lat, :lng, :category_id, :closed, :website, :phone_numbre)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :category_a_id %><br>
    <%= f.number_field :category_a_id %>
  </div>
  <div class="field">
    <%= f.label :category_b_id %><br>
    <%= f.number_field :category_b_id %>
  </div>
  <div class="field">
    <%= f.label :closed %><br>
    <%= f.check_box :closed %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :phone_numbre %><br>
    <%= f.text_field :phone_numbre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Category A</th>
      <th>Category B</th>
      <th>Closed</th>
      <th>Website</th>
      <th>Phone numbre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.address1 %></td>
        <td><%= venue.address2 %></td>
        <td><%= venue.lat %></td>
        <td><%= venue.lng %></td>
        <td><%= venue.category_a_id %></td>
        <td><%= venue.category_b_id %></td>
        <td><%= venue.closed %></td>
        <td><%= venue.website %></td>
        <td><%= venue.phone_numbre %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @venue.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @venue.address2 %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @venue.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @venue.lng %>
</p>

<p>
  <strong>Category A:</strong>
  <%= @venue.category_a_id %>
</p>
<p>
  <strong>Category B:</strong>
  <%= @venue.category_b_id %>
</p>

<p>
  <strong>Closed:</strong>
  <%= @venue.closed %>
</p>

<p>
  <strong>Website:</strong>
  <%= @venue.website %>
</p>

<p>
  <strong>Phone numbre:</strong>
  <%= @venue.phone_numbre %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>