config/routes.rb
Rails.application.routes.draw do
  resources :opendays
  resources :venues

  root 'venues#index'
  
  get "platform_a/venue", to: 'apis#get_venue_a'
  get "platform_b/venue", to: 'apis#get_venue_b'
  get "platform_c/venue", to: 'apis#get_venue_c'
  
  put "platform_a/venue", to: 'apis#update_venue_a'
  put "platform_b/venue", to: 'apis#update_venue_b'
  put "platform_c/venue", to: 'apis#update_venue_c'
  

end

app/models/openday.rb
class Openday < ActiveRecord::Base
  belongs_to :venue
  
  
end

app/controllers/opendays_controller.rb
class OpendaysController < ApplicationController
  before_action :set_openday, only: [:show, :edit, :update, :destroy]

  # GET /opendays
  # GET /opendays.json
  def index
    @opendays = Openday.all
  end

  # GET /opendays/1
  # GET /opendays/1.json
  def show
  end

  # GET /opendays/new
  def new
    @openday = Openday.new
  end

  # GET /opendays/1/edit
  def edit
  end

  # POST /opendays
  # POST /opendays.json
  def create
    @openday = Openday.new(openday_params)

    respond_to do |format|
      if @openday.save
        format.html { redirect_to @openday, notice: 'Openday was successfully created.' }
        format.json { render :show, status: :created, location: @openday }
      else
        format.html { render :new }
        format.json { render json: @openday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opendays/1
  # PATCH/PUT /opendays/1.json
  def update
    respond_to do |format|
      if @openday.update(openday_params)
        format.html { redirect_to @openday, notice: 'Openday was successfully updated.' }
        format.json { render :show, status: :ok, location: @openday }
      else
        format.html { render :edit }
        format.json { render json: @openday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opendays/1
  # DELETE /opendays/1.json
  def destroy
    @openday.destroy
    respond_to do |format|
      format.html { redirect_to opendays_url, notice: 'Openday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_openday
      @openday = Openday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def openday_params
      params.require(:openday).permit(:day, :hours, :venue_id)
    end
end

app/helpers/opendays_helper.rb
module OpendaysHelper
end

app/views/opendays/_form.html.erb
<%= form_for(@openday) do |f| %>
  <% if @openday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@openday.errors.count, "error") %> prohibited this openday from being saved:</h2>

      <ul>
      <% @openday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br>
    <%= f.text_field :venue_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opendays/edit.html.erb
<h1>Editing Openday</h1>

<%= render 'form' %>

<%= link_to 'Show', @openday %> |
<%= link_to 'Back', opendays_path %>

app/views/opendays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Opendays</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Hours</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opendays.each do |openday| %>
      <tr>
        <td><%= openday.day %></td>
        <td><%= openday.hours %></td>
        <td><%= openday.venue %></td>
        <td><%= link_to 'Show', openday %></td>
        <td><%= link_to 'Edit', edit_openday_path(openday) %></td>
        <td><%= link_to 'Destroy', openday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Openday', new_openday_path %>

app/views/opendays/new.html.erb
<h1>New Openday</h1>

<%= render 'form' %>

<%= link_to 'Back', opendays_path %>

app/views/opendays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @openday.day %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @openday.hours %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @openday.venue %>
</p>

<%= link_to 'Edit', edit_openday_path(@openday) %> |
<%= link_to 'Back', opendays_path %>